plugin: amazon.aws.aws_ec2
regions:
  - ca-central-1

filters:
  instance-state-name: running
  "tag:Environment": dev

compose:
  ansible_host: public_ip_address

keyed_groups:
  - key: tags.Name
    prefix: name
  - key: tags.Environment
    prefix: env

